/*
 * Persontjenesten API - ET
 * The Person API provides information on norwegian citizens for the norwegian public health sector, and is maintained by [Norsk helsenett](https://www.nhn.no/).  An API changelog is available [here](../static/changelog/index.html).  For more documentation and a complete integration guide, see the [NHN developer portal](https://utviklerportal.nhn.no/informasjonstjenester/persontjenesten/). 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CadastralAddressCity;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * &lt;br&gt;FREG: PostadresseIFrittFormat
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-30T07:50:48.244395087Z[Etc/UTC]", comments = "Generator version: 7.7.0-SNAPSHOT")
public class ContactAddressFreeFormPostalAddress {
  public static final String SERIALIZED_NAME_ADRESSELINJE = "adresselinje";
  @Deprecated
  @SerializedName(SERIALIZED_NAME_ADRESSELINJE)
  private List<String> adresselinje;

  public static final String SERIALIZED_NAME_ADDRESS_LINE = "addressLine";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE)
  private List<String> addressLine;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private CadastralAddressCity city;

  public ContactAddressFreeFormPostalAddress() {
  }

  @Deprecated
  public ContactAddressFreeFormPostalAddress adresselinje(List<String> adresselinje) {
    this.adresselinje = adresselinje;
    return this;
  }

  public ContactAddressFreeFormPostalAddress addAdresselinjeItem(String adresselinjeItem) {
    if (this.adresselinje == null) {
      this.adresselinje = new ArrayList<>();
    }
    this.adresselinje.add(adresselinjeItem);
    return this;
  }

   /**
   * &lt;br&gt;FREG: Adresselinje
   * @return adresselinje
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  public List<String> getAdresselinje() {
    return adresselinje;
  }

  @Deprecated
  public void setAdresselinje(List<String> adresselinje) {
    this.adresselinje = adresselinje;
  }


  public ContactAddressFreeFormPostalAddress addressLine(List<String> addressLine) {
    this.addressLine = addressLine;
    return this;
  }

  public ContactAddressFreeFormPostalAddress addAddressLineItem(String addressLineItem) {
    if (this.addressLine == null) {
      this.addressLine = new ArrayList<>();
    }
    this.addressLine.add(addressLineItem);
    return this;
  }

   /**
   * &lt;br&gt;FREG: Adresselinje
   * @return addressLine
  **/
  @javax.annotation.Nullable
  public List<String> getAddressLine() {
    return addressLine;
  }

  public void setAddressLine(List<String> addressLine) {
    this.addressLine = addressLine;
  }


  public ContactAddressFreeFormPostalAddress city(CadastralAddressCity city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @javax.annotation.Nullable
  public CadastralAddressCity getCity() {
    return city;
  }

  public void setCity(CadastralAddressCity city) {
    this.city = city;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactAddressFreeFormPostalAddress contactAddressFreeFormPostalAddress = (ContactAddressFreeFormPostalAddress) o;
    return Objects.equals(this.adresselinje, contactAddressFreeFormPostalAddress.adresselinje) &&
        Objects.equals(this.addressLine, contactAddressFreeFormPostalAddress.addressLine) &&
        Objects.equals(this.city, contactAddressFreeFormPostalAddress.city);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(adresselinje, addressLine, city);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactAddressFreeFormPostalAddress {\n");
    sb.append("    adresselinje: ").append(toIndentedString(adresselinje)).append("\n");
    sb.append("    addressLine: ").append(toIndentedString(addressLine)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("adresselinje");
    openapiFields.add("addressLine");
    openapiFields.add("city");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ContactAddressFreeFormPostalAddress
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ContactAddressFreeFormPostalAddress.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ContactAddressFreeFormPostalAddress is not found in the empty JSON string", ContactAddressFreeFormPostalAddress.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ContactAddressFreeFormPostalAddress.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ContactAddressFreeFormPostalAddress` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("adresselinje") != null && !jsonObj.get("adresselinje").isJsonNull() && !jsonObj.get("adresselinje").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `adresselinje` to be an array in the JSON string but got `%s`", jsonObj.get("adresselinje").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("addressLine") != null && !jsonObj.get("addressLine").isJsonNull() && !jsonObj.get("addressLine").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `addressLine` to be an array in the JSON string but got `%s`", jsonObj.get("addressLine").toString()));
      }
      // validate the optional field `city`
      if (jsonObj.get("city") != null && !jsonObj.get("city").isJsonNull()) {
        CadastralAddressCity.validateJsonElement(jsonObj.get("city"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ContactAddressFreeFormPostalAddress.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ContactAddressFreeFormPostalAddress' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ContactAddressFreeFormPostalAddress> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ContactAddressFreeFormPostalAddress.class));

       return (TypeAdapter<T>) new TypeAdapter<ContactAddressFreeFormPostalAddress>() {
           @Override
           public void write(JsonWriter out, ContactAddressFreeFormPostalAddress value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ContactAddressFreeFormPostalAddress read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ContactAddressFreeFormPostalAddress given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ContactAddressFreeFormPostalAddress
  * @throws IOException if the JSON string is invalid with respect to ContactAddressFreeFormPostalAddress
  */
  public static ContactAddressFreeFormPostalAddress fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ContactAddressFreeFormPostalAddress.class);
  }

 /**
  * Convert an instance of ContactAddressFreeFormPostalAddress to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

