/*
 * Persontjenesten API - ET
 * The Person API provides information on norwegian citizens for the norwegian public health sector, and is maintained by [Norsk helsenett](https://www.nhn.no/).  An API changelog is available [here](../static/changelog/index.html).  For more documentation and a complete integration guide, see the [NHN developer portal](https://utviklerportal.nhn.no/informasjonstjenester/persontjenesten/). 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.FamilyRelationRelatedPersonWithoutIdentifier;
import org.openapitools.client.model.FamilyRelationType;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Family relation between Person and a related person.  The related person has either a valid identification number (nin or d-number) or RelatedBiPerson object  &lt;br&gt;FREG: Familierelasjon
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-30T07:50:48.244395087Z[Etc/UTC]", comments = "Generator version: 7.7.0-SNAPSHOT")
public class FamilyRelation {
  public static final String SERIALIZED_NAME_REGISTERED_AT = "registeredAt";
  @SerializedName(SERIALIZED_NAME_REGISTERED_AT)
  private OffsetDateTime registeredAt;

  public static final String SERIALIZED_NAME_IS_VALID = "isValid";
  @SerializedName(SERIALIZED_NAME_IS_VALID)
  private Boolean isValid;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private String source;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private String reason;

  public static final String SERIALIZED_NAME_VALID_FROM = "validFrom";
  @SerializedName(SERIALIZED_NAME_VALID_FROM)
  private OffsetDateTime validFrom;

  public static final String SERIALIZED_NAME_VALID_TO = "validTo";
  @SerializedName(SERIALIZED_NAME_VALID_TO)
  private OffsetDateTime validTo;

  public static final String SERIALIZED_NAME_RELATED_PERSON = "relatedPerson";
  @SerializedName(SERIALIZED_NAME_RELATED_PERSON)
  private String relatedPerson;

  public static final String SERIALIZED_NAME_RELATED_PERSON_WITHOUT_IDENTIFIER = "relatedPersonWithoutIdentifier";
  @SerializedName(SERIALIZED_NAME_RELATED_PERSON_WITHOUT_IDENTIFIER)
  private FamilyRelationRelatedPersonWithoutIdentifier relatedPersonWithoutIdentifier;

  public static final String SERIALIZED_NAME_RELATED_PERSONS_ROLE = "relatedPersonsRole";
  @SerializedName(SERIALIZED_NAME_RELATED_PERSONS_ROLE)
  private FamilyRelationType relatedPersonsRole;

  public static final String SERIALIZED_NAME_MY_ROLE_FOR_RELATED_PERSON = "myRoleForRelatedPerson";
  @SerializedName(SERIALIZED_NAME_MY_ROLE_FOR_RELATED_PERSON)
  private FamilyRelationType myRoleForRelatedPerson;

  public FamilyRelation() {
  }

  public FamilyRelation registeredAt(OffsetDateTime registeredAt) {
    this.registeredAt = registeredAt;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Ajourholdstidspunkt
   * @return registeredAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getRegisteredAt() {
    return registeredAt;
  }

  public void setRegisteredAt(OffsetDateTime registeredAt) {
    this.registeredAt = registeredAt;
  }


  public FamilyRelation isValid(Boolean isValid) {
    this.isValid = isValid;
    return this;
  }

   /**
   * &lt;br&gt;FREG: ErGjeldende
   * @return isValid
  **/
  @javax.annotation.Nullable
  public Boolean getIsValid() {
    return isValid;
  }

  public void setIsValid(Boolean isValid) {
    this.isValid = isValid;
  }


  public FamilyRelation source(String source) {
    this.source = source;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Kilde
   * @return source
  **/
  @javax.annotation.Nullable
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }


  public FamilyRelation reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Aarsak
   * @return reason
  **/
  @javax.annotation.Nullable
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }


  public FamilyRelation validFrom(OffsetDateTime validFrom) {
    this.validFrom = validFrom;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Gyldighetstidspunkt
   * @return validFrom
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getValidFrom() {
    return validFrom;
  }

  public void setValidFrom(OffsetDateTime validFrom) {
    this.validFrom = validFrom;
  }


  public FamilyRelation validTo(OffsetDateTime validTo) {
    this.validTo = validTo;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Opphoerstidspunkt
   * @return validTo
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getValidTo() {
    return validTo;
  }

  public void setValidTo(OffsetDateTime validTo) {
    this.validTo = validTo;
  }


  public FamilyRelation relatedPerson(String relatedPerson) {
    this.relatedPerson = relatedPerson;
    return this;
  }

   /**
   * The identification number (nin or d-number) for the related person  &lt;br&gt;Remarks: Is null if RelatedPersonWithoutIdentifier is used
   * @return relatedPerson
  **/
  @javax.annotation.Nullable
  public String getRelatedPerson() {
    return relatedPerson;
  }

  public void setRelatedPerson(String relatedPerson) {
    this.relatedPerson = relatedPerson;
  }


  public FamilyRelation relatedPersonWithoutIdentifier(FamilyRelationRelatedPersonWithoutIdentifier relatedPersonWithoutIdentifier) {
    this.relatedPersonWithoutIdentifier = relatedPersonWithoutIdentifier;
    return this;
  }

   /**
   * Get relatedPersonWithoutIdentifier
   * @return relatedPersonWithoutIdentifier
  **/
  @javax.annotation.Nullable
  public FamilyRelationRelatedPersonWithoutIdentifier getRelatedPersonWithoutIdentifier() {
    return relatedPersonWithoutIdentifier;
  }

  public void setRelatedPersonWithoutIdentifier(FamilyRelationRelatedPersonWithoutIdentifier relatedPersonWithoutIdentifier) {
    this.relatedPersonWithoutIdentifier = relatedPersonWithoutIdentifier;
  }


  public FamilyRelation relatedPersonsRole(FamilyRelationType relatedPersonsRole) {
    this.relatedPersonsRole = relatedPersonsRole;
    return this;
  }

   /**
   * The relation type seen from the RelatedPerson or RelatedBiPersons view  Freg: RelatertPersonsRolle
   * @return relatedPersonsRole
  **/
  @javax.annotation.Nullable
  public FamilyRelationType getRelatedPersonsRole() {
    return relatedPersonsRole;
  }

  public void setRelatedPersonsRole(FamilyRelationType relatedPersonsRole) {
    this.relatedPersonsRole = relatedPersonsRole;
  }


  public FamilyRelation myRoleForRelatedPerson(FamilyRelationType myRoleForRelatedPerson) {
    this.myRoleForRelatedPerson = myRoleForRelatedPerson;
    return this;
  }

   /**
   * The relation type seen from the Persons view  Freg: MinRolleForPerson
   * @return myRoleForRelatedPerson
  **/
  @javax.annotation.Nullable
  public FamilyRelationType getMyRoleForRelatedPerson() {
    return myRoleForRelatedPerson;
  }

  public void setMyRoleForRelatedPerson(FamilyRelationType myRoleForRelatedPerson) {
    this.myRoleForRelatedPerson = myRoleForRelatedPerson;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FamilyRelation familyRelation = (FamilyRelation) o;
    return Objects.equals(this.registeredAt, familyRelation.registeredAt) &&
        Objects.equals(this.isValid, familyRelation.isValid) &&
        Objects.equals(this.source, familyRelation.source) &&
        Objects.equals(this.reason, familyRelation.reason) &&
        Objects.equals(this.validFrom, familyRelation.validFrom) &&
        Objects.equals(this.validTo, familyRelation.validTo) &&
        Objects.equals(this.relatedPerson, familyRelation.relatedPerson) &&
        Objects.equals(this.relatedPersonWithoutIdentifier, familyRelation.relatedPersonWithoutIdentifier) &&
        Objects.equals(this.relatedPersonsRole, familyRelation.relatedPersonsRole) &&
        Objects.equals(this.myRoleForRelatedPerson, familyRelation.myRoleForRelatedPerson);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(registeredAt, isValid, source, reason, validFrom, validTo, relatedPerson, relatedPersonWithoutIdentifier, relatedPersonsRole, myRoleForRelatedPerson);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FamilyRelation {\n");
    sb.append("    registeredAt: ").append(toIndentedString(registeredAt)).append("\n");
    sb.append("    isValid: ").append(toIndentedString(isValid)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    relatedPerson: ").append(toIndentedString(relatedPerson)).append("\n");
    sb.append("    relatedPersonWithoutIdentifier: ").append(toIndentedString(relatedPersonWithoutIdentifier)).append("\n");
    sb.append("    relatedPersonsRole: ").append(toIndentedString(relatedPersonsRole)).append("\n");
    sb.append("    myRoleForRelatedPerson: ").append(toIndentedString(myRoleForRelatedPerson)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("registeredAt");
    openapiFields.add("isValid");
    openapiFields.add("source");
    openapiFields.add("reason");
    openapiFields.add("validFrom");
    openapiFields.add("validTo");
    openapiFields.add("relatedPerson");
    openapiFields.add("relatedPersonWithoutIdentifier");
    openapiFields.add("relatedPersonsRole");
    openapiFields.add("myRoleForRelatedPerson");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to FamilyRelation
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FamilyRelation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FamilyRelation is not found in the empty JSON string", FamilyRelation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FamilyRelation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FamilyRelation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("source") != null && !jsonObj.get("source").isJsonNull()) && !jsonObj.get("source").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source").toString()));
      }
      if ((jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonNull()) && !jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
      if ((jsonObj.get("relatedPerson") != null && !jsonObj.get("relatedPerson").isJsonNull()) && !jsonObj.get("relatedPerson").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `relatedPerson` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relatedPerson").toString()));
      }
      // validate the optional field `relatedPersonWithoutIdentifier`
      if (jsonObj.get("relatedPersonWithoutIdentifier") != null && !jsonObj.get("relatedPersonWithoutIdentifier").isJsonNull()) {
        FamilyRelationRelatedPersonWithoutIdentifier.validateJsonElement(jsonObj.get("relatedPersonWithoutIdentifier"));
      }
      // validate the optional field `relatedPersonsRole`
      if (jsonObj.get("relatedPersonsRole") != null && !jsonObj.get("relatedPersonsRole").isJsonNull()) {
        FamilyRelationType.validateJsonElement(jsonObj.get("relatedPersonsRole"));
      }
      // validate the optional field `myRoleForRelatedPerson`
      if (jsonObj.get("myRoleForRelatedPerson") != null && !jsonObj.get("myRoleForRelatedPerson").isJsonNull()) {
        FamilyRelationType.validateJsonElement(jsonObj.get("myRoleForRelatedPerson"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FamilyRelation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FamilyRelation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FamilyRelation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FamilyRelation.class));

       return (TypeAdapter<T>) new TypeAdapter<FamilyRelation>() {
           @Override
           public void write(JsonWriter out, FamilyRelation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FamilyRelation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FamilyRelation given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FamilyRelation
  * @throws IOException if the JSON string is invalid with respect to FamilyRelation
  */
  public static FamilyRelation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FamilyRelation.class);
  }

 /**
  * Convert an instance of FamilyRelation to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

