/*
 * Persontjenesten API - ET
 * The Person API provides information on norwegian citizens for the norwegian public health sector, and is maintained by [Norsk helsenett](https://www.nhn.no/).  An API changelog is available [here](../static/changelog/index.html).  For more documentation and a complete integration guide, see the [NHN developer portal](https://utviklerportal.nhn.no/informasjonstjenester/persontjenesten/). 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.GuardianshipOrFuturePowerOfAttorneyGuardian;
import org.openapitools.client.model.GuardianshipType;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * &lt;br&gt;FREG: VergemaalRepresentasjonEllerFremtidsfullmakt
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-30T07:50:48.244395087Z[Etc/UTC]", comments = "Generator version: 7.7.0-SNAPSHOT")
public class GuardianshipOrFuturePowerOfAttorney {
  public static final String SERIALIZED_NAME_REGISTERED_AT = "registeredAt";
  @SerializedName(SERIALIZED_NAME_REGISTERED_AT)
  private OffsetDateTime registeredAt;

  public static final String SERIALIZED_NAME_IS_VALID = "isValid";
  @SerializedName(SERIALIZED_NAME_IS_VALID)
  private Boolean isValid;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private String source;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private String reason;

  public static final String SERIALIZED_NAME_VALID_FROM = "validFrom";
  @SerializedName(SERIALIZED_NAME_VALID_FROM)
  private OffsetDateTime validFrom;

  public static final String SERIALIZED_NAME_VALID_TO = "validTo";
  @SerializedName(SERIALIZED_NAME_VALID_TO)
  private OffsetDateTime validTo;

  public static final String SERIALIZED_NAME_GUARDIANSHIP_TYPE = "guardianshipType";
  @SerializedName(SERIALIZED_NAME_GUARDIANSHIP_TYPE)
  private GuardianshipType guardianshipType;

  public static final String SERIALIZED_NAME_OFFICE = "office";
  @SerializedName(SERIALIZED_NAME_OFFICE)
  private String office;

  public static final String SERIALIZED_NAME_GUARDIAN = "guardian";
  @SerializedName(SERIALIZED_NAME_GUARDIAN)
  private GuardianshipOrFuturePowerOfAttorneyGuardian guardian;

  public GuardianshipOrFuturePowerOfAttorney() {
  }

  public GuardianshipOrFuturePowerOfAttorney registeredAt(OffsetDateTime registeredAt) {
    this.registeredAt = registeredAt;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Ajourholdstidspunkt
   * @return registeredAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getRegisteredAt() {
    return registeredAt;
  }

  public void setRegisteredAt(OffsetDateTime registeredAt) {
    this.registeredAt = registeredAt;
  }


  public GuardianshipOrFuturePowerOfAttorney isValid(Boolean isValid) {
    this.isValid = isValid;
    return this;
  }

   /**
   * &lt;br&gt;FREG: ErGjeldende
   * @return isValid
  **/
  @javax.annotation.Nullable
  public Boolean getIsValid() {
    return isValid;
  }

  public void setIsValid(Boolean isValid) {
    this.isValid = isValid;
  }


  public GuardianshipOrFuturePowerOfAttorney source(String source) {
    this.source = source;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Kilde
   * @return source
  **/
  @javax.annotation.Nullable
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }


  public GuardianshipOrFuturePowerOfAttorney reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Aarsak
   * @return reason
  **/
  @javax.annotation.Nullable
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }


  public GuardianshipOrFuturePowerOfAttorney validFrom(OffsetDateTime validFrom) {
    this.validFrom = validFrom;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Gyldighetstidspunkt
   * @return validFrom
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getValidFrom() {
    return validFrom;
  }

  public void setValidFrom(OffsetDateTime validFrom) {
    this.validFrom = validFrom;
  }


  public GuardianshipOrFuturePowerOfAttorney validTo(OffsetDateTime validTo) {
    this.validTo = validTo;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Opphoerstidspunkt
   * @return validTo
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getValidTo() {
    return validTo;
  }

  public void setValidTo(OffsetDateTime validTo) {
    this.validTo = validTo;
  }


  public GuardianshipOrFuturePowerOfAttorney guardianshipType(GuardianshipType guardianshipType) {
    this.guardianshipType = guardianshipType;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Vergemaaltype
   * @return guardianshipType
  **/
  @javax.annotation.Nullable
  public GuardianshipType getGuardianshipType() {
    return guardianshipType;
  }

  public void setGuardianshipType(GuardianshipType guardianshipType) {
    this.guardianshipType = guardianshipType;
  }


  public GuardianshipOrFuturePowerOfAttorney office(String office) {
    this.office = office;
    return this;
  }

   /**
   * &lt;br&gt;FREG: Embete
   * @return office
  **/
  @javax.annotation.Nullable
  public String getOffice() {
    return office;
  }

  public void setOffice(String office) {
    this.office = office;
  }


  public GuardianshipOrFuturePowerOfAttorney guardian(GuardianshipOrFuturePowerOfAttorneyGuardian guardian) {
    this.guardian = guardian;
    return this;
  }

   /**
   * Get guardian
   * @return guardian
  **/
  @javax.annotation.Nullable
  public GuardianshipOrFuturePowerOfAttorneyGuardian getGuardian() {
    return guardian;
  }

  public void setGuardian(GuardianshipOrFuturePowerOfAttorneyGuardian guardian) {
    this.guardian = guardian;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GuardianshipOrFuturePowerOfAttorney guardianshipOrFuturePowerOfAttorney = (GuardianshipOrFuturePowerOfAttorney) o;
    return Objects.equals(this.registeredAt, guardianshipOrFuturePowerOfAttorney.registeredAt) &&
        Objects.equals(this.isValid, guardianshipOrFuturePowerOfAttorney.isValid) &&
        Objects.equals(this.source, guardianshipOrFuturePowerOfAttorney.source) &&
        Objects.equals(this.reason, guardianshipOrFuturePowerOfAttorney.reason) &&
        Objects.equals(this.validFrom, guardianshipOrFuturePowerOfAttorney.validFrom) &&
        Objects.equals(this.validTo, guardianshipOrFuturePowerOfAttorney.validTo) &&
        Objects.equals(this.guardianshipType, guardianshipOrFuturePowerOfAttorney.guardianshipType) &&
        Objects.equals(this.office, guardianshipOrFuturePowerOfAttorney.office) &&
        Objects.equals(this.guardian, guardianshipOrFuturePowerOfAttorney.guardian);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(registeredAt, isValid, source, reason, validFrom, validTo, guardianshipType, office, guardian);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GuardianshipOrFuturePowerOfAttorney {\n");
    sb.append("    registeredAt: ").append(toIndentedString(registeredAt)).append("\n");
    sb.append("    isValid: ").append(toIndentedString(isValid)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    guardianshipType: ").append(toIndentedString(guardianshipType)).append("\n");
    sb.append("    office: ").append(toIndentedString(office)).append("\n");
    sb.append("    guardian: ").append(toIndentedString(guardian)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("registeredAt");
    openapiFields.add("isValid");
    openapiFields.add("source");
    openapiFields.add("reason");
    openapiFields.add("validFrom");
    openapiFields.add("validTo");
    openapiFields.add("guardianshipType");
    openapiFields.add("office");
    openapiFields.add("guardian");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to GuardianshipOrFuturePowerOfAttorney
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GuardianshipOrFuturePowerOfAttorney.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GuardianshipOrFuturePowerOfAttorney is not found in the empty JSON string", GuardianshipOrFuturePowerOfAttorney.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GuardianshipOrFuturePowerOfAttorney.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GuardianshipOrFuturePowerOfAttorney` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("source") != null && !jsonObj.get("source").isJsonNull()) && !jsonObj.get("source").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source").toString()));
      }
      if ((jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonNull()) && !jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
      // validate the optional field `guardianshipType`
      if (jsonObj.get("guardianshipType") != null && !jsonObj.get("guardianshipType").isJsonNull()) {
        GuardianshipType.validateJsonElement(jsonObj.get("guardianshipType"));
      }
      if ((jsonObj.get("office") != null && !jsonObj.get("office").isJsonNull()) && !jsonObj.get("office").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `office` to be a primitive type in the JSON string but got `%s`", jsonObj.get("office").toString()));
      }
      // validate the optional field `guardian`
      if (jsonObj.get("guardian") != null && !jsonObj.get("guardian").isJsonNull()) {
        GuardianshipOrFuturePowerOfAttorneyGuardian.validateJsonElement(jsonObj.get("guardian"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GuardianshipOrFuturePowerOfAttorney.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GuardianshipOrFuturePowerOfAttorney' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GuardianshipOrFuturePowerOfAttorney> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GuardianshipOrFuturePowerOfAttorney.class));

       return (TypeAdapter<T>) new TypeAdapter<GuardianshipOrFuturePowerOfAttorney>() {
           @Override
           public void write(JsonWriter out, GuardianshipOrFuturePowerOfAttorney value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GuardianshipOrFuturePowerOfAttorney read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GuardianshipOrFuturePowerOfAttorney given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GuardianshipOrFuturePowerOfAttorney
  * @throws IOException if the JSON string is invalid with respect to GuardianshipOrFuturePowerOfAttorney
  */
  public static GuardianshipOrFuturePowerOfAttorney fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GuardianshipOrFuturePowerOfAttorney.class);
  }

 /**
  * Convert an instance of GuardianshipOrFuturePowerOfAttorney to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

