/*
 * Persontjenesten API - ET
 * The Person API provides information on norwegian citizens for the norwegian public health sector, and is maintained by [Norsk helsenett](https://www.nhn.no/).  An API changelog is available [here](../static/changelog/index.html).  For more documentation and a complete integration guide, see the [NHN developer portal](https://utviklerportal.nhn.no/informasjonstjenester/persontjenesten/). 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ForeignContactAddressFreeFormForeignAddress
 */
public class ForeignContactAddressFreeFormForeignAddressTest {
    private final ForeignContactAddressFreeFormForeignAddress model = new ForeignContactAddressFreeFormForeignAddress();

    /**
     * Model tests for ForeignContactAddressFreeFormForeignAddress
     */
    @Test
    public void testForeignContactAddressFreeFormForeignAddress() {
        // TODO: test ForeignContactAddressFreeFormForeignAddress
    }

    /**
     * Test the property 'addressLine'
     */
    @Test
    public void addressLineTest() {
        // TODO: test addressLine
    }

    /**
     * Test the property 'postCode'
     */
    @Test
    public void postCodeTest() {
        // TODO: test postCode
    }

    /**
     * Test the property 'cityOrPlaceName'
     */
    @Test
    public void cityOrPlaceNameTest() {
        // TODO: test cityOrPlaceName
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

}
