/*
 * Persontjenesten API - ET
 * The Person API provides information on norwegian citizens for the norwegian public health sector, and is maintained by [Norsk helsenett](https://www.nhn.no/).  An API changelog is available [here](../static/changelog/index.html).  For more documentation and a complete integration guide, see the [NHN developer portal](https://utviklerportal.nhn.no/informasjonstjenester/persontjenesten/). 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InternationalAddress
 */
public class InternationalAddressTest {
    private final InternationalAddress model = new InternationalAddress();

    /**
     * Model tests for InternationalAddress
     */
    @Test
    public void testInternationalAddress() {
        // TODO: test InternationalAddress
    }

    /**
     * Test the property 'coAddressName'
     */
    @Test
    public void coAddressNameTest() {
        // TODO: test coAddressName
    }

    /**
     * Test the property 'addressName'
     */
    @Test
    public void addressNameTest() {
        // TODO: test addressName
    }

    /**
     * Test the property 'building'
     */
    @Test
    public void buildingTest() {
        // TODO: test building
    }

    /**
     * Test the property 'floorNumber'
     */
    @Test
    public void floorNumberTest() {
        // TODO: test floorNumber
    }

    /**
     * Test the property 'housingUnit'
     */
    @Test
    public void housingUnitTest() {
        // TODO: test housingUnit
    }

    /**
     * Test the property 'postBox'
     */
    @Test
    public void postBoxTest() {
        // TODO: test postBox
    }

    /**
     * Test the property 'postCode'
     */
    @Test
    public void postCodeTest() {
        // TODO: test postCode
    }

    /**
     * Test the property 'cityOrPlaceName'
     */
    @Test
    public void cityOrPlaceNameTest() {
        // TODO: test cityOrPlaceName
    }

    /**
     * Test the property 'districtName'
     */
    @Test
    public void districtNameTest() {
        // TODO: test districtName
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

}
