/*
 * Persontjenesten API - ET
 * The Person API provides information on norwegian citizens for the norwegian public health sector, and is maintained by [Norsk helsenett](https://www.nhn.no/).  An API changelog is available [here](../static/changelog/index.html).  For more documentation and a complete integration guide, see the [NHN developer portal](https://utviklerportal.nhn.no/informasjonstjenester/persontjenesten/). 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.ParentalResponsibilityResponsibleWithoutIdentifier;
import org.openapitools.client.model.ParentalResponsibilitySubjectOfResponsibilityWithoutIdentifier;
import org.openapitools.client.model.ParentalResponsibilityType;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ParentalResponsibility
 */
public class ParentalResponsibilityTest {
    private final ParentalResponsibility model = new ParentalResponsibility();

    /**
     * Model tests for ParentalResponsibility
     */
    @Test
    public void testParentalResponsibility() {
        // TODO: test ParentalResponsibility
    }

    /**
     * Test the property 'registeredAt'
     */
    @Test
    public void registeredAtTest() {
        // TODO: test registeredAt
    }

    /**
     * Test the property 'isValid'
     */
    @Test
    public void isValidTest() {
        // TODO: test isValid
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'validFrom'
     */
    @Test
    public void validFromTest() {
        // TODO: test validFrom
    }

    /**
     * Test the property 'validTo'
     */
    @Test
    public void validToTest() {
        // TODO: test validTo
    }

    /**
     * Test the property 'responsibilityType'
     */
    @Test
    public void responsibilityTypeTest() {
        // TODO: test responsibilityType
    }

    /**
     * Test the property 'subjectOfResponsibility'
     */
    @Test
    public void subjectOfResponsibilityTest() {
        // TODO: test subjectOfResponsibility
    }

    /**
     * Test the property 'responsible'
     */
    @Test
    public void responsibleTest() {
        // TODO: test responsible
    }

    /**
     * Test the property 'responsibleOrganization'
     */
    @Test
    public void responsibleOrganizationTest() {
        // TODO: test responsibleOrganization
    }

    /**
     * Test the property 'responsibleWithoutIdentifier'
     */
    @Test
    public void responsibleWithoutIdentifierTest() {
        // TODO: test responsibleWithoutIdentifier
    }

    /**
     * Test the property 'subjectOfResponsibilityWithoutIdentifier'
     */
    @Test
    public void subjectOfResponsibilityWithoutIdentifierTest() {
        // TODO: test subjectOfResponsibilityWithoutIdentifier
    }

}
