/*
 * Persontjenesten API - ET
 * The Person API provides information on norwegian citizens for the norwegian public health sector, and is maintained by [Norsk helsenett](https://www.nhn.no/).  An API changelog is available [here](../static/changelog/index.html).  For more documentation and a complete integration guide, see the [NHN developer portal](https://utviklerportal.nhn.no/informasjonstjenester/persontjenesten/). 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.AddressConfidentiality;
import org.openapitools.client.model.AddressType;
import org.openapitools.client.model.PreferredContactAddressFreeformContactAddress;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PreferredContactAddress
 */
public class PreferredContactAddressTest {
    private final PreferredContactAddress model = new PreferredContactAddress();

    /**
     * Model tests for PreferredContactAddress
     */
    @Test
    public void testPreferredContactAddress() {
        // TODO: test PreferredContactAddress
    }

    /**
     * Test the property 'registeredAt'
     */
    @Test
    public void registeredAtTest() {
        // TODO: test registeredAt
    }

    /**
     * Test the property 'isValid'
     */
    @Test
    public void isValidTest() {
        // TODO: test isValid
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'validFrom'
     */
    @Test
    public void validFromTest() {
        // TODO: test validFrom
    }

    /**
     * Test the property 'validTo'
     */
    @Test
    public void validToTest() {
        // TODO: test validTo
    }

    /**
     * Test the property 'addressType'
     */
    @Test
    public void addressTypeTest() {
        // TODO: test addressType
    }

    /**
     * Test the property 'addressConfidentiality'
     */
    @Test
    public void addressConfidentialityTest() {
        // TODO: test addressConfidentiality
    }

    /**
     * Test the property 'freeformContactAddress'
     */
    @Test
    public void freeformContactAddressTest() {
        // TODO: test freeformContactAddress
    }

}
