/*
 * Persontjenesten API - ET
 * The Person API provides information on norwegian citizens for the norwegian public health sector, and is maintained by [Norsk helsenett](https://www.nhn.no/).  An API changelog is available [here](../static/changelog/index.html).  For more documentation and a complete integration guide, see the [NHN developer portal](https://utviklerportal.nhn.no/informasjonstjenester/persontjenesten/). 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CadastralAddressCity;
import org.openapitools.client.model.SeparatelyOccupiedUnitType;
import org.openapitools.client.model.StreetAddressAddressNumber;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PresentAddressStreetAddress
 */
public class PresentAddressStreetAddressTest {
    private final PresentAddressStreetAddress model = new PresentAddressStreetAddress();

    /**
     * Model tests for PresentAddressStreetAddress
     */
    @Test
    public void testPresentAddressStreetAddress() {
        // TODO: test PresentAddressStreetAddress
    }

    /**
     * Test the property 'municipalityNumber'
     */
    @Test
    public void municipalityNumberTest() {
        // TODO: test municipalityNumber
    }

    /**
     * Test the property 'municipalityName'
     */
    @Test
    public void municipalityNameTest() {
        // TODO: test municipalityName
    }

    /**
     * Test the property 'countyNumber'
     */
    @Test
    public void countyNumberTest() {
        // TODO: test countyNumber
    }

    /**
     * Test the property 'countyName'
     */
    @Test
    public void countyNameTest() {
        // TODO: test countyName
    }

    /**
     * Test the property 'separatelyOccupiedUnitNumber'
     */
    @Test
    public void separatelyOccupiedUnitNumberTest() {
        // TODO: test separatelyOccupiedUnitNumber
    }

    /**
     * Test the property 'separatelyOccupiedUnitType'
     */
    @Test
    public void separatelyOccupiedUnitTypeTest() {
        // TODO: test separatelyOccupiedUnitType
    }

    /**
     * Test the property 'addressName'
     */
    @Test
    public void addressNameTest() {
        // TODO: test addressName
    }

    /**
     * Test the property 'addressNumber'
     */
    @Test
    public void addressNumberTest() {
        // TODO: test addressNumber
    }

    /**
     * Test the property 'addressCode'
     */
    @Test
    public void addressCodeTest() {
        // TODO: test addressCode
    }

    /**
     * Test the property 'addressAdditionalName'
     */
    @Test
    public void addressAdditionalNameTest() {
        // TODO: test addressAdditionalName
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'coAddressName'
     */
    @Test
    public void coAddressNameTest() {
        // TODO: test coAddressName
    }

}
