/*
 * Persontjenesten API - ET
 * The Person API provides information on norwegian citizens for the norwegian public health sector, and is maintained by [Norsk helsenett](https://www.nhn.no/).  An API changelog is available [here](../static/changelog/index.html).  For more documentation and a complete integration guide, see the [NHN developer portal](https://utviklerportal.nhn.no/informasjonstjenester/persontjenesten/). 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UnknownResidence
 */
public class UnknownResidenceTest {
    private final UnknownResidence model = new UnknownResidence();

    /**
     * Model tests for UnknownResidence
     */
    @Test
    public void testUnknownResidence() {
        // TODO: test UnknownResidence
    }

    /**
     * Test the property 'municipalityNumber'
     */
    @Test
    public void municipalityNumberTest() {
        // TODO: test municipalityNumber
    }

    /**
     * Test the property 'municipalityName'
     */
    @Test
    public void municipalityNameTest() {
        // TODO: test municipalityName
    }

    /**
     * Test the property 'countyNumber'
     */
    @Test
    public void countyNumberTest() {
        // TODO: test countyNumber
    }

    /**
     * Test the property 'countyName'
     */
    @Test
    public void countyNameTest() {
        // TODO: test countyName
    }

}
